server:
  port: 9000

spring:
  application:
    name: mydb

  datasource:
    platform: mysql
    url: jdbc:mysql://database.cogrel1fuuer.ap-northeast-2.rds.amazonaws.com/mydb?autoReconnect=true # 변경해주세요
    username:  admin
    password:  Rlaaudgh7!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전